language: go

go:
  - 1.13

services:
  - docker

env:
  - GO111MODULE=on

install: true

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      script: go test --bench --benchmem -v
    - stage: build
      if: tag IS present
      env: 
        - IMAGE_NAME=quay.io/titansoft/imagepullsecret-patcher
      script: 
        - docker login -u $QUAY_IO_ACCOUNT -p $QUAY_IO_TOKEN quay.io
        - docker build -t $IMAGE_NAME:$TRAVIS_TAG .
        - docker push $IMAGE_NAME:$TRAVIS_TAG
