language: go

go:
  - 1.13

services:
  - docker

env:
  - GO111MODULE=on

install: true

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      script: go test --bench --benchmem -v
    - stage: build
      if: tag IS present
      env: IMAGE_NAME=docker.pkg.github.com/titansoft-pte-ltd/imagepullsecret-patcher
      script: 
        - docker build -t $IMAGE_NAME:$TRAVIS_TAG .
        - docker tag $IMAGE_NAME:$TRAVIS_TAG $IMAGE_NAME:latest
        - docker login -u $GITHUB_USER -p $GITHUB_TOKEN docker.pkg.github.com
        - docker push $IMAGE_NAME:$TRAVIS_TAG 
        - docker push $IMAGE_NAME:latest
